# Generated by Django 5.0.7 on 2024-07-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='porduct',
            new_name='product',
        ),
    ]
